### ISSUE TITLE
'TypeError: "prototype" is read-only' on import in Firefox 79

### ISSUE THREAD

**Issue by tstehr** [es-shims/AggregateError#12]
When importing the polyfill in Firefox 79, the following error is thrown:

```
Uncaught TypeError: "prototype" is read-only
<anonymous>   repro-firefox-es-aggregate-error/dist/main.js:1
e             repro-firefox-es-aggregate-error/dist/main.js:1
<anonymous>   repro-firefox-es-aggregate-error/dist/main.js:1
e             repro-firefox-es-aggregate-error/dist/main.js:1
<anonymous>   repro-firefox-es-aggregate-error/dist/main.js:1
<anonymous>   repro-firefox-es-aggregate-error/dist/main.js:1
```

This seems to be related that from version 79 [Firefox natively supports AggregateError](https://caniuse.com/#feat=mdn-javascript_builtins_aggregateerror). I've built a [simple test case](https://github.com/tstehr/repro-firefox-es-aggregate-error) that reproduces the problem.

For now, a workaround is to only `require` the shim if it is actually needed:

```js
if (!window.AggregateError) {
  require('es-aggregate-error').shim();
}
```

**Comment by ljharb** [comment]
Thanks for the report! Looking into it.

**Comment by ljharb** [comment]
I'll get a patch release out tomorrow. (regardless, if you really only need to install the shim, I suggest you do `require('es-aggregate-error/auto')` for a smaller bundle size)
